learning_rate: 1e-5
model_name: Qwen/Qwen1.5-1.8B-Chat
num_sensory: 32
segment_length: 512
bptt_depth: 6
num_seg_save: 8
batch_size: 1
test_length: 3000
load_from_ckpt: /home/yingqi/scratch/hmt_pretrained/qwen-1.5-1.8b-chat/model_weights_600.pth
read_token_file: huggingface_token.txt
write_token_file: write_token.txt